name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

#      - name: Run tests
#        run: ./gradlew clean test

      - name: Run TestNG XML suite
        run: java -cp .:build/libs/* org.testng.TestNG src/test/resources/xml_runners/TestNG-WebAPI.xml